version: '3'
services:
  influxdb:
    image: influxdb:1.5-alpine
    volumes:
      - influxdb-storage:/var/lib/influxdb
    ports:
      - 8086:8086
    restart: always
    networks:
      - backend
  grafana:
    image: 'grafana/grafana:latest'
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - $GRAFANA_PORT:3000
    networks:
      - backend
    depends_on:
      - influxdb
  node-red:
    build: ./node-red
    volumes:
      - node-red-storage:/data
    ports:
      - $NODE_RED_PORT:1880
    restart: always
    networks:
      - backend
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - $PORTAINER_PORT:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-storage:/data

volumes:
  grafana-storage:
  influxdb-storage:
  node-red-storage:
  mysql-storage:
  portainer-storage:

networks:
  backend:
  frontend:
